inherit_from:
  - .rubocop_todo.yml

AllCops:
  Exclude:
    - "bin/**/*"
    - "db/migrate/**/*"
    - "db/schema.rb"
    - "config/**/*"
    - "script/**/*"

Rails:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes

Metrics/ModuleLength:
  Max: 110
  Exclude:
    - "spec/controllers/users/buyers_requests_controller_spec.rb" # Just a spec file, it's fine.

Metrics/ClassLength:
  # Max: 150
  Max: 300

Metrics/LineLength:
  Max: 250

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 48
  Exclude:

Style/Documentation:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundMethodBody:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/AlignHash:
  Enabled: false

Style/IndentHash:
  Enabled: false

Style/IndentArray:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/ClosingParenthesisIndentation:
  Enabled: false

Style/AlignArray:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/AlignParameters:
  Enabled: false

Style/MultilineOperationIndentation:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 17

Metrics/PerceivedComplexity:
  Max: 17

Rails/HasAndBelongsToMany:
  Exclude:

Rails/Output:
  Exclude:
    - "db/seeds.rb"

Style/RedundantSelf:
  Enabled: false

Style/PercentLiteralDelimiters:
  Exclude:

Style/RegexpLiteral:
  Enabled: false

Style/MultilineMethodCallIndentation:
  Enabled: false
