# Configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
#   sidekiq -C config.yml
---
:verbose: false
:queues:
  - high
  - default
  - mailers
:pidfile: tmp/pids/sidekiq-0.pid
:logfile: log/sidekiq.log
:concurrency: 5
